# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - 10000:10000
    volumes:
      - ./dump:/dump
    command:
      /dump/createTwitter.sh
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 10000
    depends_on:
      - mongo
